name: Build Chromium Binaries

on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: windows-2016

    steps:
    - run: |
        dir
        git clone "https://git.eclipse.org/r/platform/eclipse.platform.swt"
        git clone "https://git.eclipse.org/r/platform/eclipse.platform.swt.binaries"
        cd eclipse.platform.swt
        git fetch "https://git.eclipse.org/r/platform/eclipse.platform.swt" refs/changes/50/175450/10 && git checkout -b change-175450-10 FETCH_HEAD
        set JAVA_HOME=%JAVA_HOME_11_X64%
        mvn clean package -P build-individual-bundles -DskipTests
        cd ..\eclipse.platform.swt.binaries
        mvn process-resources -P build-individual-bundles -Dnative=win32.win32.x86_64 -f bundles/org.eclipse.swt.browser.chromium.win32.win32.x86_64/pom.xml
