name: Build Chromium Binaries

on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: windows-2016

    steps:
    - run: |
        $Env:JAVA_HOME = $Env:JAVA_HOME_11_X64
        $Env:JAVA_HOME
