name: Build Chromium Binaries

on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: windows-2016

    steps:
    - run: |
        dir
        git clone "https://git.eclipse.org/r/platform/eclipse.platform.swt"
        git fetch "https://git.eclipse.org/r/platform/eclipse.platform.swt" refs/changes/50/175450/10 && git checkout -b change-175450-10 FETCH_HEAD
        dir
