name: Build Chromium Binaries

on: release
jobs:
  build:
    runs-on: windows-2016
# Disabled because of failing builds
#
#Error:  Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:3.0.0:run (natives-jni) on project org.eclipse.swt.browser.chromium.win32.win32.x86_64: An Ant BuildException has occured: The following error occurred while executing this line:
#Error:  D:\a\Eclipse-Chromium-Build\Eclipse-Chromium-Build\eclipse.platform.swt\bundles\org.eclipse.swt\buildSWT.xml:765: The following error occurred while executing this line:
#Error:  D:\a\Eclipse-Chromium-Build\Eclipse-Chromium-Build\eclipse.platform.swt\bundles\org.eclipse.swt\buildSWT.xml:856: exec returned: 1
#Error:  around Ant part ...<ant antfile="build.xml" target="build_libraries" />... @ 4:57 in D:\a\Eclipse-Chromium-Build\Eclipse-Chromium-Build\eclipse.platform.swt.binaries\bundles\org.eclipse.swt.browser.chromium.win32.win32.x86_64\target\antrun\build-main.xml
#
#on:
#  push:
#    branches:    
#      - main
#
#jobs:
#  build:
#    runs-on: windows-2016
#
#    steps:
#    - run: |
#        git clone "https://git.eclipse.org/r/platform/eclipse.platform.swt"
#        git clone "https://git.eclipse.org/r/platform/eclipse.platform.swt.binaries"
#        cd eclipse.platform.swt
#        git fetch "https://git.eclipse.org/r/platform/eclipse.platform.swt" refs/changes/50/175450/10 && git checkout -b change-175450-10 FETCH_HEAD
#        $Env:JAVA_HOME = $Env:JAVA_HOME_11_X64
#        mvn clean package -P build-individual-bundles -DskipTests
#        cd ..\eclipse.platform.swt.binaries
#        mvn "-Dnative=win32.win32.x86_64" -f "bundles/org.eclipse.swt.browser.chromium.win32.win32.x86_64/pom.xml" -P build-individual-bundles process-resources
#