name: Build Chromium Binaries

on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: windows-2016

    steps:
    - run: |
        set JAVA_HOME=%JAVA_HOME_11_X64%
        echo %JAVA_HOME%
