name: Build Chromium binaries for Linux

on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse/platformreleng-centos-swt-build:8

    steps:
    - run: |
        cd /home
        mkdir build
        cd build
        git clone "https://git.eclipse.org/r/platform/eclipse.platform.swt"
        git clone "https://git.eclipse.org/r/platform/eclipse.platform.swt.binaries"
        cd eclipse.platform.swt
        git fetch "https://git.eclipse.org/r/platform/eclipse.platform.swt" refs/changes/50/175450/10 && git checkout -b change-175450-10 FETCH_HEAD
        mvn clean package -P build-individual-bundles -DskipTests
        cd ..\eclipse.platform.swt.binaries
        mvn "-Dnative=gtk.linux.x86_64" -f "bundles/org.eclipse.swt.browser.chromium.gtk.linux.x86_64/pom.xml" -P build-individual-bundles process-resources
