name: Build Chromium binaries for Linux

on:
  push:
    branches:    
      - main

jobs:
  vm:
    runs-on: ubuntu-latest
    steps:
    - run: |
        cd /tmp
        mkdir build
        cd build
        echo "test" > test.txt
        pwd
        
  container:
    runs-on: ubuntu-latest
    container:
      image: eclipse/platformreleng-centos-swt-build:8
      options: -v /tmp/build:/tmp/build/:rw

    steps:
    - run: |
        ls /tmp/build
        cd /tmp
        pwd
        ls
        mkdir build
        cd build
        git clone "https://git.eclipse.org/r/platform/eclipse.platform.swt"
        git clone "https://git.eclipse.org/r/platform/eclipse.platform.swt.binaries"
        cd eclipse.platform.swt
        git fetch "https://git.eclipse.org/r/platform/eclipse.platform.swt" refs/changes/50/175450/10 && git checkout -b change-175450-10 FETCH_HEAD
        mvn clean package -P build-individual-bundles -DskipTests
        cd ..\eclipse.platform.swt.binaries
        mvn "-Dnative=gtk.linux.x86_64" -f "bundles/org.eclipse.swt.browser.chromium.gtk.linux.x86_64/pom.xml" -P build-individual-bundles process-resources
